const chars=[
 {name:"Village Hero", img:"assets/characters/village-hero/idle.png", frames:["assets/characters/village-hero/walk1.png","assets/characters/village-hero/walk2.png","assets/characters/village-hero/walk3.png","assets/characters/village-hero/walk4.png","assets/characters/village-hero/walk5.png"], talk:"assets/characters/village-hero/talk.png", happy:"assets/characters/village-hero/happy.png"},
 {name:"Village Woman", img:"assets/characters/village-woman.png"},
 {name:"Grandmother", img:"assets/characters/grandmother.png"},
 {name:"Villain Man", img:"assets/characters/villain-man.png"}
];
let scenes=[],selectedScene=0,selectedChar=chars[0],uploadedBg=null,timer=null,charImages={};
const canvas=document.getElementById("videoCanvas"),ctx=canvas.getContext("2d");
function $(id){return document.getElementById(id)}
function init(){renderChars();preloadImages();resizeCanvas();generateScenes();setTimeout(()=>drawScene(scenes[0]),500)}
function preloadImages(){chars.forEach(c=>[c.img,c.talk,c.happy,...(c.frames||[])].filter(Boolean).forEach(src=>{const img=new Image();img.src=src;charImages[src]=img}))}
function renderChars(){$("chars").innerHTML=chars.map((c,i)=>`<div class="char ${i===0?'active':''}" onclick="selectCharacter(${i})"><img src="${c.img}" onerror="this.style.display='none'"><b>${c.name}</b></div>`).join("")}
function selectCharacter(i){selectedChar=chars[i];document.querySelectorAll(".char").forEach((el,idx)=>el.classList.toggle("active",idx===i));scenes.forEach(s=>{s.character=selectedChar.name;s.characterImg=selectedChar.img;s.frames=selectedChar.frames||[];s.talk=selectedChar.talk||selectedChar.img;s.happy=selectedChar.happy||selectedChar.img});drawScene(scenes[selectedScene]||null);renderTimeline()}
function generateScenes(){const parts=$("scriptText").value.split(/[.।\n]+/).map(s=>s.trim()).filter(Boolean).slice(0,8);scenes=parts.map((text,i)=>({text,bg:$("bgSelect").value,bgImage:uploadedBg,character:selectedChar.name,characterImg:selectedChar.img,frames:selectedChar.frames||[],talk:selectedChar.talk||selectedChar.img,happy:selectedChar.happy||selectedChar.img,action:i%2?"Walking":"Talking",pos:"center"}));selectedScene=0;renderTimeline();selectScene(0)}
function renderTimeline(){$("timeline").innerHTML=scenes.map((s,i)=>`<div class="clip ${i===selectedScene?'active':''}" onclick="selectScene(${i})"><b>Scene ${i+1}</b><small>${s.text.slice(0,30)}...</small></div>`).join("")}
function selectScene(i){selectedScene=i;const s=scenes[i];if(!s)return;$("sceneEdit").value=s.text;$("actionSelect").value=s.action;$("posSelect").value=s.pos||"center";drawScene(s);renderTimeline()}
function resizeCanvas(){const f=$("formatSelect").value;if(f==="9:16"){canvas.width=720;canvas.height=1280}else{canvas.width=1280;canvas.height=720}drawScene(scenes[selectedScene]||null)}
function selectPresetBackground(){uploadedBg=null;scenes.forEach(s=>{s.bg=$("bgSelect").value;s.bgImage=null});drawScene(scenes[selectedScene]||null)}
function uploadBackground(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{uploadedBg=img;scenes.forEach(s=>s.bgImage=img);drawScene(scenes[selectedScene]||null)};img.src=r.result};r.readAsDataURL(file)}
function drawBackground(s){const w=canvas.width,h=canvas.height;if(s&&s.bgImage){ctx.drawImage(s.bgImage,0,0,w,h);return}const bg=(s&&s.bg)||$("bgSelect").value;let sky="#8bd3ff",mid="#f9e29f",ground="#22c55e";if(bg==="forest"){sky="#064e3b";mid="#14532d";ground="#052e16"}if(bg==="horror"){sky="#111827";mid="#374151";ground="#020617"}if(bg==="school"){sky="#93c5fd";mid="#fef3c7";ground="#c084fc"}if(bg==="city"){sky="#60a5fa";mid="#1e293b";ground="#0f172a"}const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,sky);g.addColorStop(.55,mid);g.addColorStop(.7,ground);ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.fillStyle="rgba(0,0,0,.14)";for(let i=0;i<5;i++){ctx.beginPath();ctx.arc((i+1)*w/6,h*.62,60,0,Math.PI*2);ctx.fill()}}
function getCharacterSource(s,p=0){const a=(s.action||"Talking").toLowerCase();if(a==="walking"&&s.frames&&s.frames.length)return s.frames[Math.floor(p*s.frames.length)%s.frames.length];if(a==="happy"&&s.happy)return s.happy;if(a==="talking"&&s.talk)return s.talk;return s.characterImg}
function drawScene(s,p=0){ctx.clearRect(0,0,canvas.width,canvas.height);drawBackground(s);const w=canvas.width,h=canvas.height;if(!s){ctx.fillStyle="#fff";ctx.font="bold 42px Arial";ctx.textAlign="center";ctx.fillText("Generate Scenes click करा",w/2,h/2);return}const src=getCharacterSource(s,p);let img=charImages[src];if(!img){img=new Image();img.src=src;charImages[src]=img}let cw=w*(w<h?.48:.25),ch=cw*1.45;let pos=s.pos||"center";let x=pos==="left"?w*.18-cw/2:pos==="right"?w*.82-cw/2:w/2-cw/2;let y=h*.73-ch;const a=(s.action||"Talking").toLowerCase();if(a==="walking")x+=Math.sin(p*Math.PI*2)*w*.08;if(a==="happy")y+=Math.sin(p*Math.PI*2)*-18;if(a==="angry"||a==="scared")x+=Math.sin(p*Math.PI*8)*8;if(img.complete&&img.naturalWidth)ctx.drawImage(img,x,y,cw,ch);else{ctx.fillStyle="#222";ctx.fillRect(x,y,cw,ch)}ctx.fillStyle="rgba(0,0,0,.72)";const boxH=w<h?120:76;roundRect(ctx,w*.06,h-boxH-30,w*.88,boxH,18,true);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font=`bold ${w<h?34:32}px Arial`;wrapText(ctx,s.text,w/2,h-boxH/2-18,w*.82,w<h?42:38)}
function roundRect(ctx,x,y,w,h,r,fill){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();if(fill)ctx.fill()}
function wrapText(ctx,text,x,y,maxWidth,lineHeight){const words=text.split(" ");let line="",lines=[];words.forEach(word=>{const test=line+word+" ";if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word+" "}else line=test});lines.push(line);const start=y-(lines.length-1)*lineHeight/2;lines.forEach((ln,i)=>ctx.fillText(ln,x,start+i*lineHeight))}
function playPreview(){if(!scenes.length)generateScenes();let i=0,frame=0;clearInterval(timer);const speed=Number($("speedSelect").value);timer=setInterval(()=>{selectedScene=i;drawScene(scenes[i],(frame%60)/60);$("progress").style.width=((i+1)/scenes.length*100)+"%";frame++;if(frame%Math.round(speed/33)===0){i=(i+1)%scenes.length;renderTimeline()}},33)}
function stopPreview(){clearInterval(timer)}
function updateCurrentScene(){if(!scenes.length)generateScenes();scenes[selectedScene].text=$("sceneEdit").value;scenes[selectedScene].action=$("actionSelect").value;scenes[selectedScene].pos=$("posSelect").value;drawScene(scenes[selectedScene]);renderTimeline()}
function duplicateScene(){if(!scenes.length)return;scenes.splice(selectedScene+1,0,{...scenes[selectedScene]});renderTimeline()}
function deleteScene(){if(!scenes.length)return;scenes.splice(selectedScene,1);selectedScene=Math.max(0,selectedScene-1);renderTimeline();drawScene(scenes[selectedScene]||null)}
function saveProject(){if(!scenes.length)generateScenes();localStorage.setItem("aiAnimateV21",JSON.stringify({script:$("scriptText").value,scenes,format:$("formatSelect").value}));alert("Project saved locally ✅")}
function loadProject(){const d=JSON.parse(localStorage.getItem("aiAnimateV21")||"null");if(!d){alert("No saved project found");return}$("scriptText").value=d.script||"";scenes=d.scenes||[];selectedScene=0;renderTimeline();drawScene(scenes[0]||null)}
async function exportVideo(){if(!scenes.length)generateScenes();$("loading").style.display="grid";resizeCanvas();const stream=canvas.captureStream(30);const rec=new MediaRecorder(stream,{mimeType:"video/webm"});const chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{const blob=new Blob(chunks,{type:"video/webm"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ai-animate-studio-v21-video.webm";a.click();$("loading").style.display="none"};rec.start();let si=0,frame=0,fps=90,total=fps*scenes.length;const render=setInterval(()=>{drawScene(scenes[si],(frame%fps)/fps);$("progress").style.width=((frame+1)/total*100)+"%";frame++;if(frame%fps===0)si++;if(frame>=total){clearInterval(render);setTimeout(()=>rec.stop(),250)}},33)}
init();