const PIN="1234";
let isAdmin=localStorage.getItem("isAdmin")==="true", user=localStorage.getItem("user")||"Guest";
const defaultChars=[
{name:"Village Hero",img:"assets/characters/village-hero/idle.png",frames:["assets/characters/village-hero/walk1.png","assets/characters/village-hero/walk2.png","assets/characters/village-hero/walk3.png","assets/characters/village-hero/walk4.png","assets/characters/village-hero/walk5.png"],talk:"assets/characters/village-hero/talk.png",happy:"assets/characters/village-hero/happy.png"},
{name:"Village Woman",img:"assets/characters/village-woman.png"},
{name:"Grandmother",img:"assets/characters/grandmother.png"},
{name:"Villain Man",img:"assets/characters/villain-man.png"}];
const defaultBgs=[{name:"Village",type:"preset",value:"village"},{name:"Forest",type:"preset",value:"forest"},{name:"School",type:"preset",value:"school"},{name:"Horror",type:"preset",value:"horror"},{name:"City",type:"preset",value:"city"}];
let chars=[...defaultChars,...JSON.parse(localStorage.getItem("adminChars")||"[]")], bgs=[...defaultBgs,...JSON.parse(localStorage.getItem("adminBgs")||"[]")];
let selectedChar=chars[0], selectedBg=bgs[0], scenes=[], selectedScene=0, imgs={}, timer=null, tempChar=null, tempBg=null, audioUrl=null;
const canvas=document.getElementById("canvas"),ctx=canvas.getContext("2d"); const $=id=>document.getElementById(id);
function page(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$(id).classList.add("active"); if(id==="admin"&&!isAdmin){alert("Admin login required");page("adminLogin")} renderAdmin();}
function adminLogin(){if($("adminPin").value===PIN){isAdmin=true;localStorage.setItem("isAdmin","true");ui();page("admin")}else alert("Wrong PIN")}
function adminLogout(){isAdmin=false;localStorage.removeItem("isAdmin");ui();page("create")}
function userLogin(){user=$("userName").value||"User";localStorage.setItem("user",user);ui();page("create")}
function ui(){$("loginStatus").textContent=user+(isAdmin?" • Admin":"");document.querySelectorAll(".adminBtn").forEach(b=>b.style.display=isAdmin?"block":"none")}
function preload(){chars.forEach(c=>[c.img,c.talk,c.happy,...(c.frames||[])].filter(Boolean).forEach(src=>{let im=new Image();im.src=src;imgs[src]=im}))}
function renderChars(){$("chars").innerHTML=chars.map((c,i)=>`<div class="card ${i==0?'active':''}" onclick="selectChar(${i})"><img src="${c.img}" onerror="this.style.display='none'"><b>${c.name}</b></div>`).join("")}
function renderBgs(){$("bgs").innerHTML=bgs.map((b,i)=>`<div class="card ${i==0?'active':''}" onclick="selectBg(${i})"><div class="bgthumb" style="${b.type==='image'?'background-image:url('+b.value+')':''}"></div><b>${b.name}</b></div>`).join("")}
function selectChar(i){selectedChar=chars[i];document.querySelectorAll("#chars .card").forEach((x,n)=>x.classList.toggle("active",n===i));scenes.forEach(s=>Object.assign(s,{character:selectedChar.name,img:selectedChar.img,frames:selectedChar.frames||[],talk:selectedChar.talk||selectedChar.img,happy:selectedChar.happy||selectedChar.img}));draw(scenes[selectedScene]);renderTimeline()}
function selectBg(i){selectedBg=bgs[i];document.querySelectorAll("#bgs .card").forEach((x,n)=>x.classList.toggle("active",n===i));scenes.forEach(s=>{s.bg=selectedBg.value;s.bgType=selectedBg.type});draw(scenes[selectedScene])}
function generateScenes(){let parts=$("scriptText").value.split(/[.।\n]+/).map(x=>x.trim()).filter(Boolean).slice(0,8);scenes=parts.map((text,i)=>({text,bg:selectedBg.value,bgType:selectedBg.type,character:selectedChar.name,img:selectedChar.img,frames:selectedChar.frames||[],talk:selectedChar.talk||selectedChar.img,happy:selectedChar.happy||selectedChar.img,action:i%2?"Walking":"Talking",pos:"center"}));selectedScene=0;renderTimeline();selectScene(0)}
function renderTimeline(){$("timeline").innerHTML=scenes.map((s,i)=>`<div class="clip ${i===selectedScene?'active':''}" onclick="selectScene(${i})"><b>Scene ${i+1}</b><br><small>${s.text.slice(0,25)}...</small></div>`).join("")}
function selectScene(i){selectedScene=i;let s=scenes[i];if(!s)return;$("sceneEdit").value=s.text;$("action").value=s.action;$("pos").value=s.pos;draw(s);renderTimeline()}
function bg(s){let w=canvas.width,h=canvas.height;if(s&&s.bgType==="image"){let im=new Image();im.src=s.bg;if(im.complete)ctx.drawImage(im,0,0,w,h);else im.onload=()=>draw(s);return}let c={village:["#8bd3ff","#f9e29f","#22c55e"],forest:["#064e3b","#14532d","#052e16"],school:["#93c5fd","#fef3c7","#c084fc"],horror:["#111827","#374151","#020617"],city:["#60a5fa","#1e293b","#0f172a"]}[s?.bg||"village"];let g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,c[0]);g.addColorStop(.55,c[1]);g.addColorStop(.7,c[2]);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}
function src(s,p=0){let a=(s.action||"Talking").toLowerCase();if(a==="walking"&&s.frames?.length)return s.frames[Math.floor(p*s.frames.length)%s.frames.length];if(a==="happy"&&s.happy)return s.happy;if(a==="talking"&&s.talk)return s.talk;return s.img}
function draw(s,p=0){ctx.clearRect(0,0,canvas.width,canvas.height);bg(s);if(!s)return;let w=canvas.width,h=canvas.height,source=src(s,p),im=imgs[source]||new Image();if(!imgs[source]){im.src=source;imgs[source]=im}let cw=w*.25,ch=cw*1.45,x=w/2-cw/2,y=h*.73-ch;if(s.pos==="left")x=w*.18-cw/2;if(s.pos==="right")x=w*.82-cw/2;if(s.action==="Walking")x+=Math.sin(p*Math.PI*2)*w*.08;if(im.complete&&im.naturalWidth)ctx.drawImage(im,x,y,cw,ch);else{ctx.fillStyle="#222";ctx.fillRect(x,y,cw,ch)}ctx.fillStyle="#000b";ctx.fillRect(w*.06,h-110,w*.88,70);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="bold 30px Arial";ctx.fillText(s.text,w/2,h-66)}
function playPreview(){if(!scenes.length)generateScenes();let i=0,f=0;clearInterval(timer);if(audioUrl){$("audio").currentTime=0;$("audio").play()}timer=setInterval(()=>{selectedScene=i;draw(scenes[i],(f%60)/60);$("progress").style.width=((i+1)/scenes.length*100)+"%";f++;if(f%67===0){i=(i+1)%scenes.length;renderTimeline()}},33)}
function stopPreview(){clearInterval(timer);$("audio").pause()}
function updateScene(){if(!scenes.length)generateScenes();Object.assign(scenes[selectedScene],{text:$("sceneEdit").value,action:$("action").value,pos:$("pos").value});draw(scenes[selectedScene]);renderTimeline()}
function duplicateScene(){scenes.splice(selectedScene+1,0,{...scenes[selectedScene]});renderTimeline()}
function deleteScene(){scenes.splice(selectedScene,1);selectedScene=Math.max(0,selectedScene-1);renderTimeline();draw(scenes[selectedScene])}
function uploadAudio(e){let f=e.target.files[0];if(!f)return;audioUrl=URL.createObjectURL(f);$("audio").src=audioUrl;$("audio").style.display="block"}
function saveProject(){localStorage.setItem("projects",JSON.stringify([{title:"Saved Project",scenes},...JSON.parse(localStorage.getItem("projects")||"[]")]));alert("Saved ✅");loadProjects()}
function loadProject(){let p=JSON.parse(localStorage.getItem("projects")||"[]")[0];if(!p)return alert("No project");scenes=p.scenes;selectScene(0)}
function loadProjects(){if(!$("projects"))return;let p=JSON.parse(localStorage.getItem("projects")||"[]");$("projects").innerHTML=p.map(x=>`<div class="asset"><b>${x.title}</b><br>${x.scenes.length} scenes</div>`).join("")||"No projects"}
async function exportVideo(){if(!scenes.length)generateScenes();$("loading").style.display="grid";let stream=canvas.captureStream(30),rec=new MediaRecorder(stream,{mimeType:"video/webm"}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>{let blob=new Blob(chunks,{type:"video/webm"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ai-animate-v22-video.webm";a.click();$("loading").style.display="none"};rec.start();let si=0,f=0,total=90*scenes.length;let r=setInterval(()=>{draw(scenes[si],(f%90)/90);f++;if(f%90===0)si++;if(f>=total){clearInterval(r);setTimeout(()=>rec.stop(),250)}},33)}
function pickChar(e){let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{tempChar=r.result;$("charPreview").innerHTML=`<img src="${tempChar}">`};r.readAsDataURL(file)}
function pickBg(e){let file=e.target.files[0];if(!file)return;let r=new FileReader();r.onload=()=>{tempBg=r.result;$("bgPreview").innerHTML=`<img src="${tempBg}" style="width:100%;height:150px;object-fit:cover">`};r.readAsDataURL(file)}
function addChar(){if(!isAdmin)return alert("Admin only");let list=JSON.parse(localStorage.getItem("adminChars")||"[]");list.push({name:$("charName").value||"New Character",img:tempChar});localStorage.setItem("adminChars",JSON.stringify(list));location.reload()}
function addBg(){if(!isAdmin)return alert("Admin only");let list=JSON.parse(localStorage.getItem("adminBgs")||"[]");list.push({name:$("bgName").value||"New Background",type:"image",value:tempBg});localStorage.setItem("adminBgs",JSON.stringify(list));location.reload()}
function renderAdmin(){if(!$("adminChars"))return;$("adminChars").innerHTML=JSON.parse(localStorage.getItem("adminChars")||"[]").map(x=>`<div class="asset">${x.name}</div>`).join("")||"No characters";$("adminBgs").innerHTML=JSON.parse(localStorage.getItem("adminBgs")||"[]").map(x=>`<div class="asset">${x.name}</div>`).join("")||"No backgrounds"}
function clearAssets(){localStorage.removeItem("adminChars");localStorage.removeItem("adminBgs");location.reload()}
ui();renderChars();renderBgs();preload();generateScenes();loadProjects();